### ISSUE TITLE
Some languages are missing

### ISSUE THREAD

**Issue by olafgrabienski** [serundeputy/get_pos#1]
The tool downloads most but not all  `.po` files which are available on https://localize.drupal.org/download. Seems that Drupal's  `iso.inc` and Backdrop's `standard.inc` are not up to date.

Using the master (Drupal) branch, two languages are missing:

- prs (Afghanistan Persian)
- tvy (Tuvan)

Using the Backdrop branch, eight languages are missing:

- fy (Frisian, Western)
- km (Khmer / Cambodian)
- ms (Bahasa Malaysia)
- os (Ossetian)
- prs (Afghanistan Persian)
- ps (Pashto)
- ta (Tamil)
- tvy (Tuvan)

**Comment by olafgrabienski** [comment]
Possible solution:

We could file issues against Backdrop and Drupal core to update the `.inc` files. (The language list in Backdrop is however much shorter than the list in Drupal. Don't know for what reason.)

Or workaround:

- Put the `.inc` file inside the folder of the tool, and change the path in `require_once` of `get_pos.php`.
- Add missing languages in the `.inc` file manually.

**Comment by serundeputy** [comment]
We should be able to add the languages to the array that is built in `get_pos.php` without modifying or breaking Backdrop or Drupal core.

Can you file an issue in backdrop/backdrop-issues with regards to the missing languages in `core/includes/standard.inc` and if that is received well, i.e. ping @quicksketch on the issue, we can file one against Drupal as well.

**Comment by olafgrabienski** [comment]
Yes, will do it!

**Comment by olafgrabienski** [comment]
Issue done: https://github.com/backdrop/backdrop-issues/issues/2610

**Comment by serundeputy** [comment]
@olafgrabienski I've added the missing languages to an array:

```php
// There are some languages misssing from iso.inc
// @see https://github.com/serundeputy/get_pos/issues/1
$missing = array(
  'tvy' => array(0 => 'Tuvan'),
  'prs' => array(0 => 'Afghanistan Persian'),
);
```

we'll see what happens with the upstream issue https://github.com/backdrop/backdrop-issues/issues/2610

thanks,
~Geoff

**Comment by olafgrabienski** [comment]
@serundeputy Thanks for adding the missing languages. I tested the script and missed Tuvan. The reason is a typo in my issue description, sorry for that! I wrote `tvy` but it has to be `tyv`.

**Comment by serundeputy** [comment]
fixed! thanks!
