### ISSUE TITLE
Counts too many files

### ISSUE THREAD

**Issue by olafgrabienski** [serundeputy/get_pos#2]
When I download 90 files, I get the message "92 files downloaded". Maybe the command `print "\n\ndone: $count files downloaded.\n";` counts *all* files in the folder, not just the downloaded?

**Comment by serundeputy** [comment]
Yes it is definitely counting all the files in the dir not just the downloads.

**Comment by serundeputy** [comment]
@olafgrabienski I've moved the destination of the downloaded files to `lang-files` and changed the count command to look for only `*.po` files so this should result in a more accurate count, although still not fool proof.

Just pull down the latest `master` to receive the improvements.

~Geoff

**Comment by olafgrabienski** [comment]
@serundeputy Thanks for the update, nice improvement!
