### ISSUE TITLE
Make it easy to download contrib modules

### ISSUE THREAD

**Issue by olafgrabienski** [serundeputy/get_pos#3]
As default, the tool downloads language files of Drupal core. To download language files of a contrib module, you have to change the file name pattern in the `wget` command.

Ideas by @serundeputy:

- a parameter for switching between different projects (Core, Views, ...)
- interactive mode to ask the user for the version number of projects

Another idea:

- create a local directory per project to store the language files

**Comment by serundeputy** [comment]
@olafgrabienski this version prompts user for `project` and `version` and downloads the `*.po` files to `lang-files/{project}-{version}` directory.

~Geoff

**Comment by olafgrabienski** [comment]
@serundeputy Thanks a lot, tested with the latest versions of Drupal core and Views, works perfect!

There's a small typo in `$version`, line 41:
`Enter the versio of the project ...` has to be:
`Enter the version of the project ...`

**Comment by serundeputy** [comment]
fixed! thanks for all the testing, proof reading, and suggestions!
